on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: docker run -d -it dnonakolesax/bmstu-course-db:latest bash 
    - uses: actions/checkout@v2
    
  test:
    runs-on: ubuntu-latest
    steps:
    - run: docker run -d -it dnonakolesax/bmstu-course-db:latest bash 
    - run: docket-run -p 4000:80 --name bmstu-course-db dnonakolesax/bmstu-course-db
    - run: docker exec -it bmstu-course-db -d python test/auth_test.py
    - uses: actions/checkout@v2